version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Instalando dependencias"
      - npm install
  pre_build:
    commands:
      - echo "Ejecutando npm audit"
      - npm audit --audit-level=low || true
  build:
    commands:
      - echo "Escaneo estático"
      - npx eslint. || true
  post_build:
    commands:
      - echo "Post build completo"
