version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Instalando dependencias..."
      - npm install
  pre_build:
    commands:
      - echo "Ejecutando fase pre_build"
  build:
    commands:
      - echo "Ejecutando build"
  post_build:
    commands:
      - echo "Post build completo"
