version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
      nodejs: 18
    commands:
      - echo "Instalando dependencias de la app..."
      - npm install
  pre_build:
    commands:
      - echo "Logueando en Amazon ECR"
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - REPOSITORY_URI=655821005352.dkr.ecr.us-east-1.amazonaws.com/vulnnodeapp
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo "imagen Docker"
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo "Pusheando imagen a ECR"
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Guardando imagen para deploy..."
      - printf '[{"name":"vulnnodeapp","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
