version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "dependencias"
      - npm install
      - npm install eslint eslint-plugin-security --save-dev

  build:
    commands:
      - echo "Analisis estático"
      - npx eslint . || true

artifacts:
  files:
    - '**/*'
