version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Instalando dependencias"
      - npm install
      - npm install eslint eslint-plugin-security --save-dev

  build:
    commands:
      - echo "Ejecutando análisis estático con ESLint"
      - npx eslint . || true

artifacts:
  files:
    - '**/*'

