version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Actualizando npm"
      - npm install -g npm@latest
      - echo "Instalando dependencias locales"
      - npm install snyk trivy
      - echo "Instalación completa"

  pre_build:
    commands:
      - echo "Escaneando vulnerabilidades de dependencias con snyk"
      - snyk test || true
      - echo "Buscando secretos con truffleHog"
      - npx trufflehog filesystem . || true

  build:
    commands:
      - echo "Escaneando con npm audit"
      - npm audit || true
      - echo "Construyendo imagen Docker"
      - docker build -t vuln-node-app .
      - echo "Escaneando imagen con Trivy"
      - trivy image vuln-node-app || true

artifacts:
  files:
    - vulnnodeapp.tar
